travis:
  secure:
    BINSTAR_TOKEN: cXmMh0qV5bhXevVtdcMf8VOVIG0zOA0cQRihCsOaDG0yPSP1tW0N40llDkDhjk80wIKMMzuwofaarESzW5i5+GTbvDMmzpeHZAEoXYUIsNTxNJMX7KcvxNdeVIGNM8tcM3a4Zp/u0cvOjDs6xSHeZPdNit3x8rDaARASwU+YZnIIY8Iieizo3LmWxRghjOdFYnr0frOshy38PI+l1ywYqsN/L8+4GqxWtkTuzK3fnI3MlwfDC8tVImjXuukHK3J78SsDdnbTBJlV0tcNV8iGa08Md55bgv9HEgFbHRSunc22lLjFRHMT10Hvl0H0HdylYkQTKC7iOwIw9D3kIp4uR+g0rDKzBuuYF+jV65+UhR5TKMiH4QIiMxBMLpB8QU1Ey58L2X2t1j06d+VZYp2UiubGNvxjXun9tWFnIotFoho1bfW0gUURNvk+fEs0O/0LpReTweNVJLc1JakT7eitFm5gaV8CNzAsNcBCpPsHWiCMQm+FD3D57q+DIJ4ONl0OOBYSDNkziJEvgB0XyV7UpGobm0xu/JTPg+Qq2op3GDxgCfILqhApTEVkMKQJv+o5yHO/JIonxCbE41xIotw8JjhQ2VROFLPGh3F3buiJ26VUbI41yoN20D4y0Bvj7HPdiBHVWNcUmkj1xYZckivnxjCE5eth/TBJiK9gqjgRw6w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
